### PR TITLE
File upload from Stream, File/Folder removal by FullName

### PR DESCRIPTION
**Pull request by viciousviper**
Implemented rudimentary File upload from Stream and File/Folder removal by FullName with associated unit tests

### CODE REVIEW

**Comment by viciousviper** [comment]
Hi @erastmorgan,

if done a bit of fiddling around with your code and managed to implement a basic File upload feature that works on Streams rather than depending on an actual `System.IO.File`.
Downloading a File to a Stream can be implemented based on your preexisting `GetFile()` method.
In addition, exposing your existing `Remove()` as a public method satisfies my use case of removing an element whose name is known beforehand - without needing to construct a File or Folder instance.

All this works well enough for me, so I'd like to ask you to consider this PR for inclusion into your library.

What surprised me is that the File upload methods create duplicates if you try to re-upload a preexisting File. Is this your intention?
I'd wish for an option to overwrite the content of an existing file instead of creating a duplicate. Would you consider offering this as an extension?

**Comment by erastmorgan** [comment]
Hi, @viciousviper , please test upload method with large file, when file size more than 1GB and more than 2GB

**Comment by viciousviper** [comment]
Hi @erastmorgan,

as you will have noticed I did not implement multi-part upload. That would have required a much more thorough refactoring than I was prepared to carry out on your project.

BTW: Do you really have a use case for uploading files larger than 2GB? I have carried out extensive tests on other Cloud services and found that even 256MB take anywhere from no less than 5 min to distinctly upwards of 15 min to upload. I for my part would be comfortable with a max supported file size of 256MB, 2GB is entirely sufficient.

**Comment by erastmorgan** [comment]
Ok @viciousviper , so please comment in your method that it is not supported large files more than 2GB. After than I think we can apply your pull request.

**Comment by viciousviper** [comment]
Done.

**Pull request merged**
